version: '3.8'

services:
  api:
    build: .
    container_name: cover-letter-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - brutaljokerz
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  brutaljokerz:
    driver: bridge 